[package]
name = "mmq"
version = "0.0.2"
description = "mmdb lookup utility"
categories = ["command-line-utilities"]
readme = "README.md"
license = "MIT"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
clap = { version = "4.6.1", features = ["cargo"] }
maxminddb = { version = "0.28.1", features = ["mmap"] }
rayon = "1.12.0"
log = "0.4.29"
env_logger = "0.11.10"
color-print = "0.3.7"
